### ISSUE TITLE
Level 0 Digimon egg

### ISSUE THREAD

**Issue by Heartlesssora** [CyanGenesis/Digimobs-Issues#10]
**Describe the bug**
If you have a level 1 digimon die it will turn into a level 0 egg and won't hatch 

**To Reproduce**
1. Kill your digimon
2. Hatch your egg 
3. Repeat till your digimon is at least level 1 this will be a big bug for beginners 
4. Kill your level 1 baby digimon 
5. There you have it a level 1 digiegg 

**Expected behavior**
Idiots not paying attention losing access to there only digimon and whining about it in servers 
**Screenshots**
![image](https://user-images.githubusercontent.com/77944327/106332617-222c4180-6255-11eb-9a4c-22762fcbf072.jpeg)

**Crash Report**
Please attach a crash report or game log if applicable

**Versions**
 Minecraft Version - 1.15 
 Forge Version 1.15 
 Digimobs Version - newest 2.04?

**Additional context**

**Comment by CyanGenesis** [comment]
You're right. They should just die permanently at that point. A much needed fix.
