### ISSUE TITLE
bugged spawning?

### ISSUE THREAD

**Issue by Tokowaffle** [CyanGenesis/Digimobs-Issues#11]
**Describe the bug**
not entirely sure if this is a bug or just empty spawn tables but some areas just dont spawn digimon
example: no rookies/champions in forests, spruce forests. No champions in mountains

**To Reproduce**
1. Go to an area where digimon should spawn
2. wait to see if anything spawns

**Expected behavior**
in the forest i expected to see gabumon and in the mountains birdramon but nothing spawned

**Screenshots**

**Crash Report**
Please attach a crash report or game log if applicable.

**Versions**
 Minecraft Version -1.15
 Forge Version1.15
 Digimobs Version -1.15

**Additional context**

**Comment by CyanGenesis** [comment]
Unfortunately I am not having this issue, both with searching around random biomes, and by going specifically to these biomes. It's possible you were just near open chunks and the upper cap on digimon spawns had been hit.

**Comment by Tokowaffle** [comment]
> Unfortunately I am not having this issue, both with searching around random biomes, and by going specifically to these biomes. It's possible you were just near open chunks and the upper cap on digimon spawns had been hit.

ive been to the same mountains and forest biomes biomes multiple times and not once seen a birdramon/gabumon/garurumon but it was also on the server so maybe its a server only bug?

**Comment by CyanGenesis** [comment]
Been playing with this some more, and it seems like it's not necessarily the biomes that are bugged, but something to do with the spawning conditions. I'm going to keep looking into it.
