### ISSUE TITLE
Digimon selection 

### ISSUE THREAD

**Issue by Enkurser** [CyanGenesis/Digimobs-Issues#15]
With the new digimon selection method you can’t see the GUI unless you’re holding your digivice, which makes it hard to use items like eg and hp floppy’s. I’d suggest either setting a specific keybind like in the old version or making it so your digimon is only unselected when you right click in the air with your digivice.

**Comment by CyanGenesis** [comment]
Or you could shift right click it, like the digivice description says.

**Comment by Enkurser** [comment]
Shift right clicking with the digivice opens the stats menu. It doesn’t make the GUI stay up while holding another item.

**Comment by CyanGenesis** [comment]
I apologize, I misspoke.
_Like the digivice description says_, you can hit ctrl+right click to debug the digivice. Part of this includes removing the selected digimon from the data of the digivice.
