### ISSUE TITLE
dont know if this is a bug or not

### ISSUE THREAD

**Issue by davepeta** [CyanGenesis/Digimobs-Issues#19]
whenever I try to join on 1.15.2 forgeoptifine it says that my forge isnt the correct version yet when I try to joing above 1.15.2 the game doesnt start

**Comment by Kinetic1000** [comment]
you need forge 31.2.47 for 1.15.2

**Comment by davepeta** [comment]
it says I need 31.2.46 how do I upgrade the forger (im using tlauncher if that helps)

**Comment by Kinetic1000** [comment]
tlauncher is piracy

**Comment by davepeta** [comment]
not really since cracked versions arent illegal last I checked since there are features locked behind the pay wall

**Comment by Kinetic1000** [comment]
there is no free minecraft. you either buy it from minecraft.net or you don't own minecraft.
