### ISSUE TITLE
Minor wild digi sneak-clicking issue

### ISSUE THREAD

**Issue by Namkcaws** [CyanGenesis/Digimobs-Issues#23]
**Describe the bug**
Sneak+rightclicking to pull up a wild digi's menu w/ the Digivice doesn't work if sneaking is set to either of the Control keys for some reason - but seemingly only that key.

I've had my sneaking & sprinting controls reversed for basically forever, so it took me a little while to figure out what was going on; I suspected there was control scheme wonkiness, but I only now decided to actually test it......sure enough I was right.

**To Reproduce**
1. Go to 'Controls' in the main menu.
2. Set sneaking to either 'Left Control' or 'Right Control'.
3. Watch the Digivice do zilch.

**Expected behavior**
Nothing other than a whacking motion.

**Screenshots**

**Crash Report**
Please attach a crash report or game log if applicable.

**Versions**
 Minecraft Version - 1.15.2
 Forge Version 31.2.48
 Digimobs Version - 2.0.7

**Additional context**

**Comment by CyanGenesis** [comment]
If you look at the digivice's description..You will see it has a function set to CTRL already, that is not bindable.
