### ISSUE TITLE
possible spawning/taming changes to fix obtainment problems

### ISSUE THREAD

**Issue by Tokowaffle** [CyanGenesis/Digimobs-Issues#29]
Due to new taming changes only digimon in rookie and below areas are obtainable meaning some lines could become unobtainable.

I think that rookies should spawn everywhere above the rookie level areas to make all lines available I think they should be a bit more uncommon as to prevent easier grinding.

I also think that the taming change could be reverted allowing all stages to be tamed but upon being tamed they will revert back to rookie with an increased chance to have their line up to the stage they were tamed.

**Comment by CyanGenesis** [comment]
Expansion of taming is planned for future releases. As for rarity of digimon lines, you now have full control of that through the config menu.
