### ISSUE TITLE
Game crashes when trying to view MetalGreymon (Alterous Mode) in the D-Terminal

### ISSUE THREAD

**Issue by day-dreamxr** [CyanGenesis/Digimobs-Issues#33]
I'm on the latest version of the mod (2.0.10) using forge version 36.1.16.

https://user-images.githubusercontent.com/87155431/125002889-95638c00-e01b-11eb-87f5-26749de420ec.mov

[crash-2021-07-08_18.36.44-client.txt](https://github.com/CyanGenesis/Digimobs-Issues/files/6787779/crash-2021-07-08_18.36.44-client.txt)

**Comment by CyanGenesis** [comment]
And it's already fixed. Redownload the mod.
