### ISSUE TITLE
Palmon Scaled incorrectly

### ISSUE THREAD

**Issue by Aaric90** [CyanGenesis/Digimobs-Issues#34]
**Describe the bug**
Ran into a Palmon that was scaled down to less than half a MC Block in size. Other palmon spawned at a usual size. I do have a screenshot of it. 

Edit- Ran into a patamon. adding that in too. Its random. Not sure how to reproduce it. Just every now and then ill run into a mini digimon. 
![digibug2](https://user-images.githubusercontent.com/87163868/125025590-90690180-e048-11eb-90f2-7302cd9fc454.png)

**To Reproduce**
Not sure you can?

**Expected behavior**
Unkown, just wanted to bring it to your attention. 

**Screenshots**
![digibug](https://user-images.githubusercontent.com/87163868/125024375-3f580e00-e046-11eb-9464-538e588fb454.jpg)

**Versions**
 Minecraft Version - 1.16.5
 Forge Version 1.16.5 - 36.1.16
 Digimobs Version - 2.0.11

**Comment by Tokowaffle** [comment]
these are natural size mutations which range from smaller models to bigger ones
