### ISSUE TITLE
Digimon/V-pet disappears if inventory is full.

### ISSUE THREAD

**Issue by Kitwastakenwastaken** [CyanGenesis/Digimobs-Issues#4]
**Describe the bug**
If your inventory is full, and you return your digimon to your v-pet, the digimon and v-pet will disappear, not return to the digibank or drop on the floor.

**To Reproduce**
1. Fill your inventory up.
2. Return your digimon to the v-pet.
3. The digimon will disappear, with no v-pet in sight, or stored in the digibank.

**Expected behavior**
I expected the v-pet to drop on the ground due to the full inventory, and then go to the digibank due to being dropped.

**Screenshots**
N/A

**Crash Report**
[latest.log](https://github.com/CyanGenesis/Digimobs-Issues/files/5860829/latest.log)

**Versions**

 Minecraft Version -1.15.2
 Forge Version-31.2.46
 Digimobs Version - 2.0.3

**Additional context**
N/A

**Comment by CyanGenesis** [comment]
Found the issue and fixed it for the next update!
