### ISSUE TITLE
Tamed digimon taking damage when you Die

### ISSUE THREAD

**Issue by Doomguy150** [CyanGenesis/Digimobs-Issues#42]
**Describe the bug**
On digimob beyond when you leave your digimon at your base when you die by a player it for some reason take damage from nothing

**To Reproduce**
1. leave your digimob at your base outside of v-pet
2. ask some one  to kill you
3. check if digimon have bin damage out of nowhere

**Expected behavior**
when kill from a player tamed digimob take damage from nowhere 

**Versions**
 Minecraft Version - 1.16.5
 Forge Version - 36.1.30
 Digimobs Version - Digimobs-1.16.5-2.0.13

**Comment by CyanGenesis** [comment]
Or..it's more likely some one or some thing hit your digimon. There is no relation between dying and entities taking damage.

**Comment by Tokowaffle** [comment]
turns out it was my astral sorcery perks causing a lightning chain to hit his digimon as he respawned
