### ISSUE TITLE
Storing Digimon in V-Pet with Full Bag causes the Digimon to Dissapear

### ISSUE THREAD

**Issue by TamerM43** [CyanGenesis/Digimobs-Issues#5]
**Describe the bug**
If your bag is full and you don't have a V-Pet item with you, and you try to store your Digimon into a V-Pet using the Digivice Item, no V-Pet item is created, and your Digimon disappears.

**To Reproduce**
1. Make sure to have a full bag with no V-Pet item
2. Go to the Digivice and go to the action that says "Store Digimon in V-Pet"
3. Click on the Digimob action button (default is '.')

**Expected behavior**
A message to pop up stating that there is not enough space in the inventory, and for the action to be cancelled.

**Versions**
 Minecraft Version - 1.15.2
 Forge Version - 31.2.47
 Digimobs Version - 2.0.3

**Additional context**

**Comment by CyanGenesis** [comment]
#4
