### ISSUE TITLE
Digimobs on Servers?

### ISSUE THREAD

**Issue by Charmanderxerneas** [CyanGenesis/Digimobs-Issues#53]
Hello! I apologize if this question seems silly or if this information is somewhere else, but I have had difficulty with it so I just wanted to ask about this directly.

I have been really enjoying playing this mod by myself! But my boyfriend has been wanting to play it with me on a server. Now, I'm not the most skilled at server management so I usually just use simple third parties to make Minecraft servers. The two I have tried are aternos and ploudos.

However, when we've tried making a server together, the mod just fails to work at all and the server refuses to even open. I've spent over an hour trouble shooting and trying to get it to work, but I can't seem to figure it out. As I mentioned before, I've only tried making a server with the mod on aternos and ploudos, and I do not know how to make a server outside of those two options. I am trying to use the 1.1.8d version of digimobs and have installed it and forge 1.12.2 to the server. It is the only mod on the server. It refuses to work.

Is there an issue with the mod that prevents it from being on a server? I was under the impression that there was an official server for it, but I just wanted a smaller server for just me and my boyfriend. Am I just going about the wrong way to make a server with the mod on it?

Thank you for your time and for the mod. It's still fun regardless but it would be awesome to play it with friends!

**Comment by CyanGenesis** [comment]
You can find a solution to this issue in our discord faq section. But in general, the 1.12 versions are no longer supported.
