### ISSUE TITLE
Huanglong Ore doesn't work with Blast Furnace 

### ISSUE THREAD

**Issue by Chameleonpot** [CyanGenesis/Digimobs-Issues#58]
**Describe the bug**
When you try to put Huanglong Ore into a Blast Furnace it doesn't smelt
**To Reproduce**

**Expected behavior**
I expected the Huanglong Ore to smelt in the Blast Furnace
**Screenshots**

**Crash Report**
Please attach a crash report or game log if applicable.

**Versions**
 Minecraft Version - 1.16.5
 Forge Version - 36.2.20 
 Digimobs Version - 2.1.2

**Additional context**

**Comment by CyanGenesis** [comment]
Not a bug, but I'll go ahead and add it as a suggestion.
