### ISSUE TITLE
Game crash when player die

### ISSUE THREAD

**Issue by ColaLiao** [CyanGenesis/Digimobs-Issues#62]
**Describe the bug**
Game crash when player die

**To Reproduce**
Get killed

[crash-2022-03-26_23.02.43-client.txt](https://github.com/CyanGenesis/Digimobs-Issues/files/8355714/crash-2022-03-26_23.02.43-client.txt)

**Versions**
 Minecraft Version - 1.16.5
 Forge Version - 1.16.5 - 36.2.20
 Digimobs Version - digimobs-1.16.5-2.1.5

**Comment by CyanGenesis** [comment]
Update the mod.
