### ISSUE TITLE
Failed Evolution that changes the Evolution when you degenerate a Digimon from an ugly champion

### ISSUE THREAD

**Issue by Nuttehstar** [CyanGenesis/Digimobs-Issues#63]
Okay so, earlier someone from the Digimob Beyond server overfed their digimon and it turned into those ugly digimon champions. I was told that this was temporary so the evolution would be fixed easily, how I dunno. So I decided to test this theory by going onto Creative and taming a digimon as a test dummy. I tamed a Gabumon and overfed its favorite food and it digivolved into Nanimon. Oddly, the Nanimon still had the name "Gabumon" as its nickname so I suspected it was just a bug. After I degenerate it thinking it'll turn back into Gabumon, it instead degenerated into Elecmon.

I checked its Evolution and instead of Nanimon, it was that centaur digimon. I gave the Elecmon a bond and nothing changes its evolution.

So I think maybe if a digimon failed its evolution and reverts to rookie, its evolution is resetted to something different.

**Comment by Nuttehstar** [comment]
Okay so I tested it further and I dunno, but I tested this on other digimon and none of their evolution changed once reverted back to their normal states. so I dunno if it's just the Gabumon line that is screwed up or something.

**Comment by CyanGenesis** [comment]
It does appear that Gabumon has an extra line that he shouldn't. This has been remedied now for the next update.
