### ISSUE TITLE
cant use skills

### ISSUE THREAD

**Issue by mariocool22** [CyanGenesis/Digimobs-Issues#69]
**Describe the bug**
same as title i try but it just says cant do this right now though i have set it and have little more then 3/4ths of my energys
**To Reproduce**
just does it

**Expected behavior**
use its skill

**Versions**
 Minecraft Version -1.16.5
 Forge Version 36.2.34
 Digimobs Version - 1.19a

**Comment by CyanGenesis** [comment]
You need to provide a LOT more information than this for me to even attempt to reproduce this. As I currently have no issues using specials.

**Comment by mariocool22** [comment]
idk why but it just happens i see other digimon do there skills but i cant
