### ISSUE TITLE
Evolution line doesnt seem to be working properly

### ISSUE THREAD

**Issue by harmonizationz** [CyanGenesis/Digimobs-Issues#70]
I used the evoliner and did little to nothing, when I go to the digivolution line it doesnt work on my digimon and I feed it like 100 card games

![image](https://user-images.githubusercontent.com/110957428/183808010-85b83012-fb3c-4ace-bf6a-6c335be501cb.png)

 Digimobs Version - Digimobs(2.1.9a)

**Comment by CyanGenesis** [comment]
It works fine. Please review the changelogs for changes to the bond amounts, or check the #faqs channel of the discord.

**Comment by harmonizationz** [comment]
Why when i search other youtubers their evo line works? also they have other layout for it, Am I missing something in the mod?

![image](https://user-images.githubusercontent.com/110957428/183815647-5cef6016-73cc-497c-a937-986fb25b3e92.png)

**Comment by harmonizationz** [comment]
when i search other youtubers their evo line works? also they have other layout for it, Am I missing something in the mod?
 
![image](https://user-images.githubusercontent.com/110957428/183815812-77d31752-08f9-433c-a832-82e824719b6e.png)
