### ISSUE TITLE
[1.16.5] Unable to finish loading the game to the main menu screen when used with Mekanism

### ISSUE THREAD

**Issue by WolfBV** [CyanGenesis/Digimobs-Issues#77]
Forge: 36.2.34
digimobs-1.16.5-2.1.9a
Mekanism-1.16.5-10.1.2.457

https://pastebin.com/c00zE1Up

**Comment by WolfBV** [comment]
This also happens when using the lotr mod: lotr-1.16-renewed-5.5
and lycanite's mobs: lycanitesmobs-1.16.5-2.3.3.3
with digimobs

**Comment by WolfBV** [comment]
This also occurs when using digimobs with lord of the rings: renewed: lotr-1.16-renewed-5.5, lycanite's mobs: lycanitesmobs-1.16.5-2.3.3.3, and DivineRPG: DivineRPG-1.8.27

**Comment by CyanGenesis** [comment]
This is a common issue for Macs, if you happen to be playing on one.

**Comment by WolfBV** [comment]
Thanks.
