### ISSUE TITLE
Can't feed my digimob

### ISSUE THREAD

**Issue by KiltCross** [CyanGenesis/Digimobs-Issues#78]
When I tried to feed my digimon nothing happend.

1. Put the food in hand
2. Select the digimon (making sure the selection cross in him)
3. Right click
4. Nothing

**Expected behavior**
In the four step the digimon should have been feed.

**Versions**
 Minecraft Version - 1.15.2
 Forge Version 31.2.57
 Digimobs Version - 2.0.9

**Comment by CyanGenesis** [comment]
Update your mod. The 1.15 versions were just alpha versions of the rebuild. Hunger was likely not implemented at that point.
