### ISSUE TITLE
About allowing me to use mods in the server

### ISSUE THREAD

**Issue by VigilLC** [CyanGenesis/Digimobs-Issues#79]
Dear author, hello, I am a Minecraft player from China.
I watched Digimon when I was a kid and I really liked it.  Today I accidentally found this mod you made, I like this mod very much, including my friends, they also like it, so I hope to get your authorization to use this mod on my server, I will mark you as its creator.  I hope you'll allow me to use it!
Looking forward to your reply.

**Comment by CyanGenesis** [comment]
Anyone can use this mod on a server :)
