### ISSUE TITLE
Errors when Going to Over World

### ISSUE THREAD

**Issue by FlyingATigger** [CyanGenesis/Digimobs-Issues#83]
**Describe the bug**

**To Reproduce**
![Screenshot 2023-04-19 130502](https://user-images.githubusercontent.com/131295494/233161980-d6189401-f749-49f5-a53d-4704effe58ef.png)

1. Go to 'Digital World'
2. Click on 'Mess around for a bit then click to go back to the over world'
3. Scroll down to 'then your stuck loading terrain could it be my other modsmods'

**Expected behavior**

**Screenshots**

**Crash Report**
Please attach a crash report or game log if applicable.

**Versions**
 Minecraft Version -12.2
 Forge Version
 Digimobs Version -

**Additional context**

**Comment by CyanGenesis** [comment]
1.12.2 is no longer supported. Update to the latest version.
