### ISSUE TITLE
odd crashes

### ISSUE THREAD

**Issue by Vadewolf** [CyanGenesis/Digimobs-Issues#90]
**Describe the bug**

render bugs

**To Reproduce**
1. Go to '...' spawn in world 

**Expected behavior**

not to crash please 

**Screenshots**

**Crash Report**
Please attach a crash report or game log if applicable.
[crash-2024-12-04_10.44.21-client.txt](https://github.com/user-attachments/files/18011689/crash-2024-12-04_10.44.21-client.txt)
[crash-2024-12-04_10.53.12-client.txt](https://github.com/user-attachments/files/18011690/crash-2024-12-04_10.53.12-client.txt)

**Versions**
 Minecraft Version -1.20.1
 Forge Version 47.1.43
 Digimobs Version - 2.4.0d

**Additional context**
really odd crashes since the digimon do exist

**Comment by CyanGenesis** [comment]
Remove whichever mod you have that is conflicting with GeckoLib.

**Comment by Vadewolf** [comment]
i would love to know wat mod it is please cause nothing is matching up
